# Site settings
title: Shelley-Godwin Archive
email: info@shelleygodwinarchive.org
description: > # The Shelley-Godwin Archive will provide the digitized manuscripts of Percy Bysshe Shelley,
  Mary Wollstonecraft Shelley, William Godwin, and Mary Wollstonecraft, bringing together online for the first
  time ever the widely dispersed handwritten legacy of this uniquely gifted family of writers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shelleygodwinarchive.org" # the base hostname & protocol for your site
twitter_username: shelleygodwin
github_username:  mith_umd

# S-GA Specific Global Variables
searchservice: "http://54.166.24.46/"

# Build settings
markdown: kramdown
highligher: pygments

# Top nav
navigation:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Explore the Archive
   url: /explore/
 - title: Search
   url: /search/
 - title: Using the Archive
   url: /using-the-archive/

# Includes
include: ['_pages']

# Excludes
exclude: [components, node_modules, offline]

kramdown:
  input: GFM
